CREATE TABLE CATEGORIES (
  ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100)        NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL
)

CREATE TABLE PRODUCTS (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100)        NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRICE       DOUBLE       NOT NULL,
  FK_CATEGORY_ID BIGINT    NOT NULL,
  CONSTRAINT FK_PROD_TO_CATEG FOREIGN KEY (FK_CATEGORY_ID)
  REFERENCES CATEGORIES(ID)
)